"""
We unlearned CCP alignment from Qwen3.6-35B-A3B: censored/propaganda answers 89.8% → 2.8%, general benchmarks within ~1 point (open weights)
Starter automation script generated by Musfira AI.
Replace the placeholder logic below with your implementation.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"


def query_local_llm(prompt: str, model: str = "llama3") -> str:
    resp = requests.post(
        OLLAMA_URL,
        json={"model": model, "prompt": prompt, "stream": False},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json().get("response", "")


def main() -> None:
    prompt = "Summarize the latest update on: We unlearned CCP alignment from Qwen3.6-35B-A3B: censored/propaganda answers 89.8% → 2.8%, general benchmarks within ~1 point (open weights)"
    print(query_local_llm(prompt))


if __name__ == "__main__":
    main()
